---
- name: Aplicació de regles de gestió d'usuari
  hosts: windows
  vars:
	ansible_user: Administrator
	ansible_password: mandamas
	ansible_shell_type: cmd
  tasks:

	- name: Copiar
  	copy:
    	src: /home/tic/firewall_ac.ps1
    	dest: 'C:\Users\{{ ansible_user }}\AppData\Local\Temp\command.ps1'
    	owner: "{{ ansible_user }}"
    	mode: '0777'
	- name: Llegir contingut del script
  	win_shell: 'C:\Users\{{ ansible_user }}\AppData\Local\Temp\command.ps1'
